CREATE DATABASE SYSVENDA

USE [SYSVENDA]
GO

/****** Object:  Table [dbo].[USUARIOS]    Script Date: 12/02/2018 08:23:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[USUARIOS](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[NOME] [varchar](50) NOT NULL,
	[LOGIN] [varchar](15) NOT NULL,
	[SENHA] [varchar](8) NOT NULL,
	[BLOQUEADO] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [SYSVENDA]
GO

/****** Object:  Table [dbo].[PRODUTOS]    Script Date: 12/02/2018 08:23:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PRODUTOS](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[DESCRICAO] [varchar](45) NOT NULL,
	[PRECO] [numeric](15, 2) NOT NULL,
	[UNIDADE_MEDIDA] [varchar](5) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PRODUTOS] ADD  DEFAULT ('UN') FOR [UNIDADE_MEDIDA]
GO


USE [SYSVENDA]
GO

/****** Object:  Table [dbo].[PESSOAS]    Script Date: 17/02/2018 13:19:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PESSOAS](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[TIPO] [varchar](1) NOT NULL,
	[RAZAO_SOCIAL_NOME] [varchar](50) NOT NULL,
	[NOME_FANTASIA_APELIDO] [varchar](50) NULL,
	[CNPJ_CPF] [varchar](14) NULL,
	[PAIS] [varchar](20) NULL,
	[ESTADO] [varchar](2) NULL,
	[CIDADE] [varchar](50) NULL,
	[CEP] [varchar](8) NULL,
	[BAIRRO] [varchar](50) NULL,
	[ENDERECO] [varchar](50) NULL,
	[NUMERO] [varchar](8) NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[CNPJ_CPF] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [SYSVENDA]
GO

/****** Object:  Table [dbo].[CLASSIFICACOES_PESSOAS]    Script Date: 12/02/2018 08:27:22 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CLASSIFICACOES_PESSOAS](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[DESCRICAO] [varchar](30) NOT NULL,
	[PESSOA] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CLASSIFICACOES_PESSOAS]  WITH CHECK ADD  CONSTRAINT [FK_PESSOAS] FOREIGN KEY([PESSOA])
REFERENCES [dbo].[PESSOAS] ([CODIGO])
GO

ALTER TABLE [dbo].[CLASSIFICACOES_PESSOAS] CHECK CONSTRAINT [FK_PESSOAS]
GO


USE [SYSVENDA]
GO

/****** Object:  Table [dbo].[MESAS]    Script Date: 12/02/2018 08:24:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MESAS](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[DESCRICAO] [varchar](20) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [SYSVENDA]
GO

/****** Object:  Table [dbo].[GARCONS]    Script Date: 12/02/2018 08:24:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[GARCONS](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[NOME] [varchar](45) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [SYSVENDA]
GO

/****** Object:  Table [dbo].[FORMAS_PAGAMENTOS]    Script Date: 12/02/2018 08:24:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FORMAS_PAGAMENTOS](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[DESCRICAO] [varchar](20) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [SYSVENDA]
GO

/****** Object:  Table [dbo].[EMPRESAS]    Script Date: 12/02/2018 08:24:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[EMPRESAS](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[PESSOA] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[EMPRESAS]  WITH CHECK ADD  CONSTRAINT [FK_EMPRESAS_PESSOAS] FOREIGN KEY([PESSOA])
REFERENCES [dbo].[PESSOAS] ([CODIGO])
GO

ALTER TABLE [dbo].[EMPRESAS] CHECK CONSTRAINT [FK_EMPRESAS_PESSOAS]
GO

USE [SYSVENDA]
GO

/****** Object:  Table [dbo].[COMANDAS]    Script Date: 12/02/2018 08:27:59 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[COMANDAS](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[DATA_HORA] [datetime] NULL,
	[GARCOM] [int] NULL,
	[MESA] [int] NULL,
	[STATUS] [char](1) NULL,
	[FORMA_PAGAMENTO] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[COMANDAS] ADD  DEFAULT (getdate()) FOR [DATA_HORA]
GO

ALTER TABLE [dbo].[COMANDAS]  WITH CHECK ADD  CONSTRAINT [FK_COMANDA_FORMA_PAGAMENTO] FOREIGN KEY([FORMA_PAGAMENTO])
REFERENCES [dbo].[FORMAS_PAGAMENTOS] ([CODIGO])
GO

ALTER TABLE [dbo].[COMANDAS] CHECK CONSTRAINT [FK_COMANDA_FORMA_PAGAMENTO]
GO

ALTER TABLE [dbo].[COMANDAS]  WITH CHECK ADD  CONSTRAINT [FK_COMANDA_GARCO] FOREIGN KEY([GARCOM])
REFERENCES [dbo].[GARCONS] ([CODIGO])
GO

ALTER TABLE [dbo].[COMANDAS] CHECK CONSTRAINT [FK_COMANDA_GARCO]
GO

ALTER TABLE [dbo].[COMANDAS]  WITH CHECK ADD  CONSTRAINT [FK_COMANDA_MESA] FOREIGN KEY([MESA])
REFERENCES [dbo].[MESAS] ([CODIGO])
GO

ALTER TABLE [dbo].[COMANDAS] CHECK CONSTRAINT [FK_COMANDA_MESA]
GO


USE [SYSVENDA]
GO

/****** Object:  Table [dbo].[COMANDAS_ITENS]    Script Date: 12/02/2018 08:28:21 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[COMANDAS_ITENS](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[COMANDA] [int] NOT NULL,
	[PRODUTO] [int] NOT NULL,
	[VALOR] [numeric](15, 2) NULL,
	[QUANTIDADE] [numeric](15, 0) NULL,
	[DESCONTO] [numeric](15, 0) NULL,
	[VALOR_TOTAL_LIQUIDO] [numeric](15, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[COMANDAS_ITENS]  WITH CHECK ADD  CONSTRAINT [FK_ITEM_COMANDA] FOREIGN KEY([COMANDA])
REFERENCES [dbo].[COMANDAS] ([CODIGO])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[COMANDAS_ITENS] CHECK CONSTRAINT [FK_ITEM_COMANDA]
GO

ALTER TABLE [dbo].[COMANDAS_ITENS]  WITH CHECK ADD  CONSTRAINT [FK_ITEM_PRODUTO] FOREIGN KEY([PRODUTO])
REFERENCES [dbo].[PRODUTOS] ([CODIGO])
GO

ALTER TABLE [dbo].[COMANDAS_ITENS] CHECK CONSTRAINT [FK_ITEM_PRODUTO]
GO


USE [SYSVENDA]
GO

/****** Object:  Table [dbo].[CONTAS_PAGAR]    Script Date: 12/02/2018 08:28:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CONTAS_PAGAR](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[EMPRESA] [int] NOT NULL,
	[DATA_CADASTRO] [date] NOT NULL,
	[DATA] [date] NOT NULL,
	[RECEBEDOR] [int] NOT NULL,
	[OBSERVACAO] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CONTAS_PAGAR] ADD  DEFAULT (getdate()) FOR [DATA_CADASTRO]
GO

ALTER TABLE [dbo].[CONTAS_PAGAR]  WITH CHECK ADD  CONSTRAINT [FK_CONTASPAGAR_PESSOAS] FOREIGN KEY([RECEBEDOR])
REFERENCES [dbo].[PESSOAS] ([CODIGO])
GO

ALTER TABLE [dbo].[CONTAS_PAGAR] CHECK CONSTRAINT [FK_CONTASPAGAR_PESSOAS]
GO


USE [SYSVENDA]
GO

/****** Object:  Table [dbo].[CONTAS_PAGAR_PARCELAS]    Script Date: 12/02/2018 08:28:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CONTAS_PAGAR_PARCELAS](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[CONTA_PAGAR] [int] NOT NULL,
	[TITULO] [varchar](20) NOT NULL,
	[PARCELA] [int] NOT NULL,
	[VALOR] [numeric](15, 2) NOT NULL,
	[JUROS] [numeric](15, 2) NOT NULL,
	[MULTA] [numeric](15, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CONTAS_PAGAR_PARCELAS]  WITH CHECK ADD  CONSTRAINT [FK_PARCELAS_CONTASPAGAR] FOREIGN KEY([CONTA_PAGAR])
REFERENCES [dbo].[CONTAS_PAGAR] ([CODIGO])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[CONTAS_PAGAR_PARCELAS] CHECK CONSTRAINT [FK_PARCELAS_CONTASPAGAR]
GO


USE [SYSVENDA]
GO

/****** Object:  Table [dbo].[CONTAS_RECEBER]    Script Date: 12/02/2018 08:29:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CONTAS_RECEBER](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[EMPRESA] [int] NOT NULL,
	[DATA_CADASTRO] [date] NOT NULL,
	[DATA] [date] NOT NULL,
	[PAGADOR] [int] NOT NULL,
	[OBSERVACAO] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CONTAS_RECEBER] ADD  DEFAULT (getdate()) FOR [DATA_CADASTRO]
GO

ALTER TABLE [dbo].[CONTAS_RECEBER]  WITH CHECK ADD  CONSTRAINT [FK_CONTASRECEBER_PESSOAS] FOREIGN KEY([PAGADOR])
REFERENCES [dbo].[PESSOAS] ([CODIGO])
GO

ALTER TABLE [dbo].[CONTAS_RECEBER] CHECK CONSTRAINT [FK_CONTASRECEBER_PESSOAS]
GO


USE [SYSVENDA]
GO

/****** Object:  Table [dbo].[CONTAS_RECEBER_PARCELAS]    Script Date: 12/02/2018 08:29:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CONTAS_RECEBER_PARCELAS](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[CONTA_RECEBER] [int] NOT NULL,
	[TITULO] [varchar](20) NOT NULL,
	[PARCELA] [int] NOT NULL,
	[VALOR] [numeric](15, 2) NOT NULL,
	[JUROS] [numeric](15, 2) NOT NULL,
	[MULTA] [numeric](15, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CONTAS_RECEBER_PARCELAS]  WITH CHECK ADD  CONSTRAINT [FK_PARCELAS_CONTASRECEBER] FOREIGN KEY([CONTA_RECEBER])
REFERENCES [dbo].[CONTAS_RECEBER] ([CODIGO])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[CONTAS_RECEBER_PARCELAS] CHECK CONSTRAINT [FK_PARCELAS_CONTASRECEBER]
GO


USE [SYSVENDA]
GO

/****** Object:  Table [dbo].[CONTAS_RECEBIMENTOS]    Script Date: 12/02/2018 08:29:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CONTAS_RECEBIMENTOS](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[CONTA_RECEBER_PARCELA] [int] NOT NULL,
	[DATA_CADASTRO] [date] NOT NULL,
	[DATA] [date] NOT NULL,
	[VALOR] [numeric](15, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CONTAS_RECEBIMENTOS] ADD  DEFAULT (getdate()) FOR [DATA_CADASTRO]
GO

ALTER TABLE [dbo].[CONTAS_RECEBIMENTOS]  WITH CHECK ADD  CONSTRAINT [FK_RECEBIMENTOS_ARECEBER] FOREIGN KEY([CONTA_RECEBER_PARCELA])
REFERENCES [dbo].[CONTAS_RECEBER_PARCELAS] ([CODIGO])
GO

ALTER TABLE [dbo].[CONTAS_RECEBIMENTOS] CHECK CONSTRAINT [FK_RECEBIMENTOS_ARECEBER]
GO


USE [SYSVENDA]
GO

/****** Object:  Table [dbo].[CONTAS_PAGAMENTOS]    Script Date: 12/02/2018 08:30:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CONTAS_PAGAMENTOS](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[CONTA_PAGAR_PARCELA] [int] NOT NULL,
	[DATA_CADASTRO] [date] NOT NULL,
	[DATA] [date] NOT NULL,
	[VALOR] [numeric](15, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CONTAS_PAGAMENTOS] ADD  DEFAULT (getdate()) FOR [DATA_CADASTRO]
GO

ALTER TABLE [dbo].[CONTAS_PAGAMENTOS]  WITH CHECK ADD  CONSTRAINT [FK_PAGAMENTOS_APAGAR] FOREIGN KEY([CONTA_PAGAR_PARCELA])
REFERENCES [dbo].[CONTAS_PAGAR_PARCELAS] ([CODIGO])
GO

ALTER TABLE [dbo].[CONTAS_PAGAMENTOS] CHECK CONSTRAINT [FK_PAGAMENTOS_APAGAR]
GO


